export {
  getLife,
  getBattleLife,
  getStrength,
  getBattleStrength,
  getBattleMode,
  getLocation,
  getPlayId,
  getUsername,
  getFirstName,
  getLastName,
  getWinRate,
  getLostRate,
  getWorldDominationRank,
  getTear,
  getBank,
  getToken,
  getAutoBattleMode,
} from './MainActions';
